build.sbt

Based on https://github.com/apache/spark/blob/master/project/SparkBuild.scala#L368
cc @etrain

Retain meta-inf/services in assembly

---

src/main/scala/nodes/learning/BlockLinearMapper.scala
src/main/scala/utils/MatrixUtils.scala
src/test/scala/nodes/stats/LinearRectifierSuite.scala

Made what matrix utils I trivially could be generic

---

src/main/scala/nodes/util/AllSparseFeatures.scala
src/main/scala/nodes/util/CommonSparseFeatures.scala
src/main/scala/workflow/ConcretePipeline.scala
src/test/scala/nodes/misc/SparseFeatureVectorizerSuite.scala

(to prevent bugs when repeated in the Pipeline DAG)
@etrain @shivaram 
I think these are the only estimators/transformers that are currently non-deterministic (other than the K-means++ in the imagenet research branch)
If I'm wrong about that we should fix whatever other nodes aren't too.

Made the sparse feature estimators deterministic

---

src/main/scala/loaders/TimitFeaturesDataLoader.scala

timit data loader bug fix

---

bin/run-main.sh
bin/run-pipeline.sh
build.sbt

SBT updates for sonatype release

---

build.sbt

Fix the mlmatrix dependency issue in build.sbt

---

src/main/scala/pipelines/images/voc/VOCSIFTFisher.scala

voc bug fix in num images per column

---

src/main/scala/evaluation/BinaryClassifierEvaluator.scala
src/main/scala/loaders/AmazonReviewsDataLoader.scala
src/main/scala/nodes/learning/LogisticRegressionModel.scala
src/main/scala/pipelines/text/AmazonReviewsPipeline.scala
src/main/scala/pipelines/text/NewsgroupsPipeline.scala
src/test/scala/nodes/learning/LogisticRegressionModelSuite.scala

Moved over the Amazon pipeline

---

src/main/scala/pipelines/images/imagenet/ImageNetSiftLcsFV.scala
src/main/scala/pipelines/images/voc/VOCSIFTFisher.scala
src/main/scala/pipelines/speech/TimitPipeline.scala
src/main/scala/pipelines/text/AmazonReviewsPipeline.scala
src/main/scala/pipelines/text/NewsgroupsPipeline.scala
src/main/scala/workflow/ConcretePipeline.scala
src/main/scala/workflow/Pipeline.scala
src/main/scala/workflow/Transformer.scala

Closes issue #170 
Allows you to control what optimizer (if any) is used when executing a pipeline, defaulting to the current Optimizer object
@etrain

Apply the optimizer automatically

---

src/main/scala/utils/MatrixUtils.scala

fix for issue #177

---

src/main/scala/nodes/nlp/HashingTF.scala
src/main/scala/nodes/nlp/NGramsHashingTF.scala
src/test/scala/nodes/nlp/HashingTFSuite.scala
src/test/scala/nodes/nlp/NGramsHashingTFSuite.scala

Added hashing trick nodes

---

src/main/scala/nodes/learning/BlockWeightedLeastSquares.scala
src/main/scala/nodes/util/VectorSplitter.scala
src/test/scala/nodes/learning/BlockWeightedLeastSquaresSuite.scala

Handle non-uniform blocks in WeightedLeastSquares

---

src/main/scala/nodes/images/Cropper.scala

This is a follow on to #204 which adds a `Cropper` transformer.
Closes #211

Adding image cropper class.

---

src/main/scala/nodes/learning/BlockWeightedLeastSquares.scala
src/main/scala/utils/MatrixUtils.scala
src/test/scala/nodes/learning/BlockWeightedLeastSquaresSuite.scala

Handle empty partitions in WeightedLeastSquares

---

src/main/scala/nodes/util/ClassLabelIndicators.scala
src/test/scala/nodes/util/ClassLabelIndicatorsSuite.scala

Closes #197 
Added unit tests.

Adding class label indicators validation.

---

bin/run-pipeline.sh

Addresses #198 
Tested locally on OSX in several combinations of situations, and verified that env variables were set as expected.

Adding logic to set OMP_NUM_THREADS appropriately

---

src/main/scala/workflow/ConcretePipeline.scala
src/main/scala/workflow/DefaultOptimizer.scala
src/main/scala/workflow/Estimator.scala
src/main/scala/workflow/LabelEstimator.scala
src/main/scala/workflow/Node.scala
src/main/scala/workflow/NodeOptimizationRule.scala
src/main/scala/workflow/OptimizableNodes.scala
src/main/scala/workflow/WorkflowUtils.scala
src/test/scala/workflow/NodeOptimizationRuleSuite.scala
src/test/scala/workflow/WorkflowUtilsSuite.scala

Added a node-level optimization rule

---

sbt/sbt
src/main/scala/utils/images/Image.scala

Fixes to get builds to work again

---

src/test/scala/nodes/learning/PCASuite.scala

cc @shivaram based on a conversation we had offline.

Switching norm from singular to frobenius due to conditioning issues.

---

RELEASE.md

Add release notes for snapshots

---

src/main/scala/nodes/learning/BlockLinearMapper.scala
src/main/scala/nodes/learning/DistributedPCA.scala
src/main/scala/nodes/learning/GaussianMixtureModel.scala
src/main/scala/nodes/learning/Gradient.scala
src/main/scala/nodes/learning/KMeansPlusPlus.scala
src/main/scala/nodes/learning/LinearMapper.scala
src/main/scala/nodes/learning/LocalLeastSquaresEstimator.scala
src/main/scala/nodes/stats/CosineRandomFeatures.scala

This is safer for handling empty partitions.
cc @ericmjonas @Vaishaal

Replace rowsToMatrix with rowsToMatrixIter

---

src/main/scala/pipelines/images/cifar/LinearPixels.scala
src/main/scala/pipelines/images/cifar/RandomCifar.scala
src/main/scala/pipelines/images/cifar/RandomPatchCifar.scala
src/main/scala/pipelines/images/imagenet/ImageNetSiftLcsFV.scala
src/main/scala/pipelines/images/mnist/MnistRandomFFT.scala
src/main/scala/pipelines/images/voc/VOCSIFTFisher.scala
src/main/scala/pipelines/speech/TimitPipeline.scala
src/main/scala/pipelines/text/AmazonReviewsPipeline.scala
src/main/scala/pipelines/text/NewsgroupsPipeline.scala

Closes #241 
This is in support of making the current PR at amplab/keystone-integration-tests less hacky, and sets a nice foundation for us to continue to test these pipelines in the future.
cc @shivaram @tomerk

Returning a 'Pipeline' from run method of existing examples.

---

src/main/scala/nodes/learning/BlockLinearMapper.scala
src/main/scala/nodes/learning/BlockWeightedLeastSquares.scala
src/main/scala/workflow/AutoCacheRule.scala
src/main/scala/workflow/DefaultOptimizer.scala
src/main/scala/workflow/Node.scala
src/main/scala/workflow/SparkUtilWrapper.scala
src/main/scala/workflow/WeightedNode.scala
src/main/scala/workflow/WorkflowUtils.scala
src/test/scala/workflow/AutoCacheRuleSuite.scala

Added auto-caching rules w/ aggressive naive, and greedy profiling strategies
@etrain 
@shivaram

Auto caching rule

---

src/main/scala/workflow/ConcretePipeline.scala
src/test/scala/workflow/PipelineSuite.scala

Fix to multiple execution

---

RELEASE.md

Updated the KeystoneML release guide

---

src/main/scala/nodes/images/FisherVector.scala
src/main/scala/nodes/images/external/FisherVector.scala
src/main/scala/nodes/learning/BlockLinearMapper.scala
src/main/scala/nodes/learning/CostModel.scala
src/main/scala/nodes/learning/DistributedPCA.scala
src/main/scala/nodes/learning/LBFGS.scala
src/main/scala/nodes/learning/LeastSquaresEstimator.scala
src/main/scala/nodes/learning/LinearMapper.scala
src/main/scala/nodes/learning/PCA.scala
src/main/scala/pipelines/images/imagenet/ImageNetSiftLcsFV.scala
src/main/scala/pipelines/images/voc/VOCSIFTFisher.scala
src/test/scala/nodes/learning/PCASuite.scala

Added optimizable gmm fisher vector, column pca estimators

---

EC2.md

Will update the website to match this once merged.

Fixing up EC2 launch documentation.

---

build.sbt

Bumping default spark and hadoop versions.

---

src/main/scala/workflow/AutoCacheRule.scala
src/main/scala/workflow/ConcretePipeline.scala
src/main/scala/workflow/Estimator.scala
src/main/scala/workflow/GatherTransformer.scala
src/main/scala/workflow/LabelEstimator.scala
src/main/scala/workflow/Node.scala
src/main/scala/workflow/OptimizableNodes.scala
src/main/scala/workflow/Transformer.scala
src/test/scala/workflow/PipelineSuite.scala

@etrain @shivaram 
This is key for hyperparameter tuning, checkpointing, lazy block solvers, etc.

Allowed DAG branches to be taken lazily

---

src/main/scala/workflow/AutoCacheRule.scala

Made autocaching much faster for complex DAGs

---

Makefile

Closes #268 
Thanks for reporting @zhaozhang

Pointing to objects located on S3.

---

CONTRIBUTORS.md
build.sbt
src/main/scala/nodes/nlp/POSTagger.scala
src/test/scala/nodes/nlp/POSTaggerSuite.scala

I tested the POS model on Spark and it works well. Since it's pretty heavy (~300mb) I also created a case class taking a broadcasted model as parameter. Did not test it on a Spark cluster but it may help with several executors.
I also used the TaggedSequence offered by the Epic lib as a data structure returned by the node. It as richer features to work with.
Let me know if you see anything else :)
Cheers

Pos tagging

---

src/main/scala/nodes/nlp/NER.scala
src/test/scala/nodes/nlp/NERSuite.scala

Hey guys, on the same idea as the POS tagger, here is the NER. As @etrain said, it would be better if the Keystone API wouldn't expose Epic's interfaces so I'll work on this as a next step.
Let me know if you see anything here, I built it pretty much the same way I did with the POS Tagger.
Thanks,
Nicolas

Named entity recognition

---

src/main/cpp/EncEval.cxx

I'm pretty sure this is what screwed me up last semester. Sigh.

Samples GMM ref wasn't released in EncEval code

---

src/main/scala/workflow/graph/ChainUtils.scala

Compiles and tests pass locally

[HOTFIX] Fix broken build by adding ClassTag to ChainUtils

---

src/main/scala/nodes/learning/internal/ReWeightedLeastSquares.scala
src/test/scala/nodes/learning/BlockWeightedLeastSquaresSuite.scala

Also added a test case. Fixes a bug found by @ericmjonas

Handle empty partitions ReWeightedLeastSquares

---

src/main/scala/evaluation/AugmentedExamplesEvaluator.scala
src/main/scala/evaluation/BinaryClassifierEvaluator.scala
src/main/scala/evaluation/Evaluator.scala
src/main/scala/evaluation/MeanAveragePrecisionEvaluator.scala
src/main/scala/evaluation/MulticlassClassifierEvaluator.scala
src/main/scala/pipelines/images/cifar/LinearPixels.scala
src/main/scala/pipelines/images/cifar/RandomCifar.scala
src/main/scala/pipelines/images/cifar/RandomPatchCifar.scala
src/main/scala/pipelines/images/cifar/RandomPatchCifarAugmented.scala
src/main/scala/pipelines/images/cifar/RandomPatchCifarAugmentedKernel.scala
src/main/scala/pipelines/images/cifar/RandomPatchCifarKernel.scala
src/main/scala/pipelines/images/imagenet/ImageNetSiftLcsFV.scala
src/main/scala/pipelines/images/mnist/MnistRandomFFT.scala
src/main/scala/pipelines/images/voc/VOCSIFTFisher.scala
src/main/scala/pipelines/speech/TimitPipeline.scala
src/main/scala/pipelines/text/AmazonReviewsPipeline.scala
src/main/scala/pipelines/text/NewsgroupsPipeline.scala
src/test/scala/evaluation/BinaryClassifierEvaluatorSuite.scala
src/test/scala/evaluation/MeanAveragePrecisionSuite.scala
src/test/scala/evaluation/MulticlassClassifierEvaluatorSuite.scala

Evaluatorinterface
